/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ptidej_newjava_restrictJNI_Main */

#ifndef _Included_net_ptidej_newjava_restrictJNI_Main
#define _Included_net_ptidej_newjava_restrictJNI_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_ptidej_newjava_restrictJNI_Main
 * Method:    foo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_ptidej_newjava_restrictJNI_Main_foo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
