/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ptidej_newjava_restrictJNI_A */

#ifndef _Included_net_ptidej_newjava_restrictJNI_A
#define _Included_net_ptidej_newjava_restrictJNI_A
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_ptidej_newjava_restrictJNI_A
 * Method:    bar
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_ptidej_newjava_restrictJNI_A_bar
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
